version: "3"
services:
  ubuntu_node:
    build: .
    image: bolt-spec
    ports:
      - "20022:22"
    container_name: ubuntu_node
  puppet_5_node:
    image:  bolt-spec
    depends_on:
      - ubuntu_node
    ports:
      - "20023:22"
  puppet_6_node:
    image:  bolt-spec
    depends_on:
      - ubuntu_node
    ports:
      - "20024:22"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    volumes:
      - ./fixtures/puppetdb/custom_source:/docker-entrypoint-initdb.d
  puppetdb:
    build:
      context: .
      dockerfile: Dockerfile.puppetdb
      args:
        hostname: bolt-puppetdb
    environment:
      - "USE_PUPPETSERVER=false"
      - "CERTNAME=pdb"
    image: puppetdb
    ports:
      # 8081 is a common port
      - "18081:8081"

  puppetserver:
    build:
      context: .
      dockerfile: Dockerfile.puppetserver
    image: puppet-server
    ports:
      - "8140:8140"
    volumes:
      - ./fixtures/modules:/etc/puppetlabs/code/modules

  omiserver:
    hostname: omiserver
    domainname: bolt.test
    # must use Samba AD for DNS
    dns:
      - 172.22.0.100
      - 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile.omiserver
      args:
        BOLT_PASSWORD: bolt
    ports:
      - "45985:5985"
      - "45986:5986"
    environment:
      KRB5_REALM: ${KRB5_REALM:-BOLT.TEST}
      KRB5_KDC: ${KRB5_KDC:-samba-ad.bolt.test}
      SMB_DOMAIN: ${SMB_DOMAIN:-BOLT}
      SMB_ADMIN: Administrator
      SMB_ADMIN_PASSWORD: ${SMB_ADMIN_PASSWORD:-B0ltrules!}
    depends_on:
      - samba-ad
    networks:
      BOLT.TEST:

  samba-ad:
    hostname: samba-ad
    domainname: bolt.test
    # must use itself for DNS
    dns:
      - 172.22.0.100
      - 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile.samba-ad
    # SYS_ADMIN necessary for samba-tool domain provision
    # otherwise set_nt_acl_no_snum: fset_nt_acl returned NT_STATUS_ACCESS_DENIED
    cap_add:
      - SYS_ADMIN
    ports:
      - "88:88"
      - "464:464"
    environment:
      KRB5_REALM: ${KRB5_REALM:-BOLT.TEST}
      KRB5_KDC: ${KRB5_KDC:-localhost}
      KRB5_ADMINSERVER: ${KRB5_ADMINSERVER}
      SMB_DOMAIN: ${SMB_DOMAIN:-BOLT}
      SMB_ADMIN_PASSWORD: ${SMB_ADMIN_PASSWORD:-B0ltrules!}
    networks:
      BOLT.TEST:
        ipv4_address: 172.22.0.100
        aliases:
          - samba-ad.bolt.test

networks:
  BOLT.TEST:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
